services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./php:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./php
    volumes:
      - ./php:/var/www/html
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  mariadb:
    image: mariadb:11.7.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  logparser:
    build:
      context: .
      dockerfile: Dockerfile.logparser
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
    env_file: .env
    networks:
      - app-network
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: